services:
  web:
    container_name: web
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/src
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+asyncpg://postgres:pass@db/vee}
      - SECRET_KEY=${SECRET_KEY:-VEE_SECRET}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${SECRET_KEY:-30}
    ports:
      - "8000:8000"
    networks:
      - vee

  db:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=vee
    networks:
      - vee
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d vee" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 2s

  test_web:
    container_name: test_web
    build: .
    depends_on:
      test_db:
        condition: service_healthy
    volumes:
      - ./:/src
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+asyncpg://postgres:pass@test_db/vee}
      - SECRET_KEY=${SECRET_KEY:-VEE_SECRET}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${SECRET_KEY:-30}
    ports:
      - 8000:8000
    networks:
      - vee

  test_db:
    container_name: test_db
    image: postgres:15-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=vee
    networks:
      - vee
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d vee" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 2s

volumes:
  postgres_data:

networks:
  vee:
